finance/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('expenses.urls')),
    path('income/',include('income.urls')),
     path('auth/',include('authentication.urls')),
]

income/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name="income"

urlpatterns = [
    path('',views.income, name='income'),
    path('add/',views.incomeadd, name='add'),
    path('edit/<int:id>',views.incomeedit, name='edit'),
    path('delete/<int:id>',views.incomedelete, name='delete'),
    path('stat/',views.stat, name='stat'),
    path('statapi/',views.stat_api, name='statapi'),
    path('data/',views.exportdata, name='export'),
]

income/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.

class Income(models.Model):
    owner = models.ForeignKey(to=User,on_delete=models.CASCADE,default=None)
    description=models.TextField(max_length=255)
    source=models.CharField(max_length=255)
    date=models.DateField(default=datetime.datetime.now)
    amount=models.CharField(max_length=25)

    def __str__(self):
        return self.owner.username+" "+self.source+" "+self.amount

class Source(models.Model):
    name=models.CharField(max_length=255)

    def __str__(self):
        return self.name

income/views.py
from django.shortcuts import redirect, render
from .models import *
from expenses.models import Userpref
from django.contrib.auth.decorators import login_required
import os
from django.conf import settings as s
import json
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponse, JsonResponse
import csv
# Create your views here.

@login_required(login_url='/auth/login/')
def income(request):
    data=Income.objects.filter(owner=request.user)
    try:
        pref=Userpref.objects.get(username=request.user)
    except:
        pref=" "

    paginator = Paginator(data, 5)
    page_number = request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    context={'pref':pref,'data':data,'page_obj': page_obj}
    return render(request,'income/income.html',context=context)

@login_required(login_url='/auth/login/')
def incomeadd(request):
    if request.method == 'POST':
        user=request.user
        amount=request.POST['amount']
        source=request.POST['source']
        date=request.POST['date']
        description=request.POST['description']
        user=User.objects.get(username=user)
        # print(amount, source, date, description)
        ent=Income.objects.create(owner=user, amount=amount, source=source, date=date, description=description)
        ent.save()
        messages.success(request,"New Record Added Successfully")
        return redirect('income:income')
    source=Source.objects.all()
    context={
        'source':source
    }
    
    return render(request,'income/incomeadd.html',context)

@login_required(login_url='/auth/login/')
def incomeedit(request,id):
    if request.method=='GET':
        ele=Income.objects.get(id=id)
        context={
            'edit':True,
            'ele':ele,
            'source':Source.objects.all()
        }
        return render(request,'income/incomeadd.html',context)

    if request.method=='POST':
        ele=Income.objects.get(id=id)
        ele.amount=request.POST['amount']
        ele.source=request.POST['source']
        ele.date=request.POST['date']
        ele.description=request.POST['description']
        ele.save()
        messages.success(request,"Editted Successfully")
        return redirect('income:income')

@login_required(login_url='/auth/login/')
def incomedelete(request,id):
    ele=Income.objects.get(id=id)
    ele.delete()
    messages.success(request,"Deleted Successfully")
    return redirect('income:income')

def stat(request):
    return render(request,'income/stats.html')

def getcat(exp):
    return exp.source
    

def stat_api(request):
    now=datetime.datetime.today()
    year=now-datetime.timedelta(days=30*12)
    exp=Income.objects.filter(owner=request.user,date__gte=year,date__lte=now)
    final={}
    # print(exp)
    # print(Income.objects.all())
    all_cat=[]
    f=Source.objects.all()
    for i in f:
        all_cat.append(i.name)
        
    def get_amt(cat):
        ans=0
        expd=exp.filter(source=cat)
        for i in expd:
            ans+=int(i.amount)
            # print(i.amount)
        return ans

    for y in all_cat:
        final[y]=get_amt(y)

    return JsonResponse({'inc_result':final},safe=False)

@login_required(login_url='/auth/login/')
def exportdata(request):
    data=Income.objects.filter(owner=request.user)
    res=HttpResponse(content_type='text/csv')
    res['Content-Disposition']='attachment; filename=Income_Data'+str(datetime.datetime.now())+'.csv'
    writer=csv.writer(res)
    writer.writerow(['Amount','Source','Date','Description'])

    for i in data:
        writer.writerow([i.amount,i.source,i.date,i.description])
    return res

templates/income/income.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Income Section{% endblock title %}
{% block content %}

  <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->

  <a href="{% url 'income:add' %}"><button type="submit" class="btn btn-success btn-sm mt-1 mb-1" >Add income</button></a>
  <a href="{% url 'income:export' %}" class="btn btn-danger btn-sm">Export data</a>
  <div class="table-responsive mt-3">
    <table class="table table-lg table-borderless table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Number</th>
          <th scope="col">Amount ({{pref.currency|slice:"0:3"}}) </th>
          <th scope="col">Description</th>
          <th scope="col">Source</th>
          <th scope="col">Date</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for i in page_obj %}
        <tr>
          <td scope="row">{{ forloop.counter }}</td>
          <td>{{i.amount}}</td>
          <td>{{i.description}}</td>
          <td>{{i.source}}</td>
          <td>{{i.date}}</td>
          <td><a href="{% url 'income:edit' i.pk %}" class="btn btn-sm btn-outline-success">Edit</a>
          <a href="{% url 'income:delete' i.pk %}" class="btn btn-sm btn-outline-danger">Delete</a></td>
        </tr>
        {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>

  <div class="pagination-container">
    <div class="page-item">
      Showing page {{page_obj.number}} of {{ page_obj.paginator.num_pages }}
    </div>

    <ul class="pagination justify-content-end">
      {% if page_obj.has_previous %}
      <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}><a class="page-link" href="?page=1">&laquo; 1</a></li>
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}

      {% if page_obj.has_next %}
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages}} &raquo;</a></li>
      {% endif %}

      </ul>
      <div class="chart">
        <canvas id="myChart" style="height: 50%; width:50%;"></canvas>
      </div>
   
 
      <script src="{% static 'js/incomestats.js' %}"> </script>
{% endblock %}

templates/income/incomeadd.html
{% extends 'main.html' %}

{% block title %}
{% if edit %}
Edit Income
{% else %}
Add New Income
{% endif %}
{% endblock title %}

{% block content %}
{% if edit %}
  <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->
  <h2></h2>
  <form class="form" method="post" action="{% url 'income:edit' ele.pk%}">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" >Amount</label>
        <input class="form-control" type="text" name="amount" value="{{ele.amount}}"/>
    </div>  
    <div class="mb-3">
        <label class="form-label">Source</label>
        <select class="form-select form-select-md" name='source'>
            <option value="{{ele.source}}" selected>{{ele.source}}</option>
           {% for i in source %}
            <option value="{{i.name}}">{{i.name}}</option>
           {% endfor %}
        </select>
    </div>  
    <div class="mb-3">
        <label class="form-label" >Date {{ele.date}}</label>
        <input placeholder="Date" name="date" class="form-control" type="text" onfocus="(this.type='date')" value="{{ele.date|date:'Y-m-d'}}" id="date">
        <!-- <input class="form-control" value="{{ele.date|date:'d/m/y'}}" type="date" name="date" /> -->
    </div>  
    <div class="mb-3">
        <label class="form-label" >Description</label>
        <input class="form-control" type="text" name="description" value="{{ele.description}}" />
    </div>  
      <input type="submit" class="btn btn-primary" />
  </form>
  {% else %}

  <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->
  <h2></h2>
  <form class="form" method="post" action="{% url 'income:add' %}">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" >Amount</label>
        <input class="form-control" type="text" name="amount"/>
    </div>  
    <div class="mb-3">
        <label class="form-label">Source</label>
        <select class="form-select form-select-md" name='source'>
           {% for i in source %}
            <option value="{{i.name}}">{{i.name}}</option>
           {% endfor %}
        </select>
    </div>  
    <div class="mb-3">
        <label class="form-label" >Date</label>
        <input placeholder="Date" name="date" class="form-control" type="text" onfocus="(this.type='date')" id="date">
    </div>  
    <div class="mb-3">
        <label class="form-label" >Description</label>
        <input class="form-control" type="text" name="description"/>
    </div>  
      <input type="submit" class="btn btn-primary" />
  </form>
  {% endif %}
  {% endblock content %}

templates/income/stats.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Income Statics{% endblock title %}
{% block content %}

<div class="chart">
    <canvas id="myChart2" class="chart-item mt-5"></canvas>
    <canvas id="myChart3" class="chart-item mt-5"></canvas>
</div>
<style>
   
    .chart{
         height:100vh; width:auto;
    }
</style>

 
<script src="{% static 'js/incomestats.js' %}"> </script>
{% endblock content %}