authentication/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt
app_name='auth'

urlpatterns = [
    path('login/',views.Login.as_view(), name='login'),
    path('logout/',views.Logout.as_view(), name='logout'),
    path('signup/',views.signup, name='signup'),
    path('reset/',views.reset, name='reset'),
    path('valid-email/',csrf_exempt(views.ValidateEmail.as_view())),
    path('valid-username/',csrf_exempt(views.ValidateUsername.as_view())),
    path('activate/<uid>/<token>',views.activate.as_view(),name="activate")
]

expenses/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name='expenses'

urlpatterns = [
    path('',views.dahboard, name='home'),
    path('expenses/',views.expenses, name='expenses'),
    path('expenses/add/',views.expensesadd, name='add'),
    path('expenses/edit/<int:id>',views.expensesedit, name='edit'),
    path('expenses/delete/<int:id>',views.expensesdelete, name='delete'),
    path('settings/',views.settings, name='settings'),
    path('stat/',views.stat, name='stat'),
    path('expenses/statapi/',views.stat_api, name='statapi'),
    path('data/',views.exportdata, name='export'),
]

finance/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('expenses.urls')),
    path('income/',include('income.urls')),
     path('auth/',include('authentication.urls')),
]

income/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name="income"

urlpatterns = [
    path('',views.income, name='income'),
    path('add/',views.incomeadd, name='add'),
    path('edit/<int:id>',views.incomeedit, name='edit'),
    path('delete/<int:id>',views.incomedelete, name='delete'),
    path('stat/',views.stat, name='stat'),
    path('statapi/',views.stat_api, name='statapi'),
    path('data/',views.exportdata, name='export'),
]

templates/dashboard.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
<div class="container">

{% if user.is_authenticated %}
          <form method="post" action="{% url 'auth:logout' %}">
            {% csrf_token %}
           <button class="btn btn-md btn-danger" type="submit">Logout</button>
          </form>
          
{% else %}
          <a class="btn btn-md btn-success" href="{% url 'auth:login' %}">Login</a>
{% endif %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">About the project</h1>
  </div>
  <ul>
    <li>
      Manage your incomes and expenditures.
    </li>
    <li>
      Perform CRUD operations.
    </li>
    <li>
      Set your preferred currency in settings.
    </li>
  </ul>
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">More Features</h1>
  </div>
  <ul>
    <li>
      User Authentication by email.
    </li>
    <li>
      Intreactive charts for data Visualisation.
    </li>
    <li>
      Export data in csv format.
    </li>
  </ul>
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Technologies Used</h1>
</div>
<ul>
  <li>
    Django in backend.
  </li>
  <li>
    Bootstrap, javascript in frontend.
  </li>
  <li>
    Postgresql for database.
  </li> <li>
    Custom API for data retrival.
  </li>
</ul>
<a href="https://drive.google.com/file/d/1nhx3-DIL4mVkgitD-dAZo4eIWN8jAdH4/view?usp=sharing" class="button btn btn-md btn-outline-danger">Demo Video</a>
</div>
{% endblock content %}

templates/expenses.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Expenses Section{% endblock title %}
{% block content %}

  <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->

  <a href="{% url 'expenses:add' %}"><button type="submit" class="btn btn-success btn-sm mt-1 mb-1" >Add Expenses</button></a>
  <a href="{% url 'expenses:export' %}" class="btn btn-danger btn-sm">Export data</a>
  <div class="table-responsive mt-3">
    <table class="table table-lg table-borderless table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Number</th>
          <th scope="col"> Amount ({{pref.currency|slice:"0:3"}}) </th>
          <th scope="col">Description</th>
          <th scope="col">Category</th>
          <th scope="col">Date</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for i in page_obj %}
        <tr>
          <td scope="row">{{ forloop.counter }}</td>
          <td>{{i.amount}}</td>
          <td>{{i.description}}</td>
          <td>{{i.category}}</td>
          <td>{{i.date}}</td>
          <td><a href="{% url 'expenses:edit' i.pk %}" class="btn btn-sm btn-outline-success">Edit</a>
          <a href="{% url 'expenses:delete' i.pk %}" class="btn btn-sm btn-outline-danger">Delete</a></td>
        </tr>
        {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>

  <div class="pagination-container">
    <div class="page-item">
      Showing page {{page_obj.number}} of {{ page_obj.paginator.num_pages }}
    </div>

    <ul class="pagination justify-content-end">
      {% if page_obj.has_previous %}
      <li {% if page_obj.number == 1 %} class="page-item active" {% endif %}><a class="page-link" href="?page=1">&laquo; 1</a></li>
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
      {% endif %}

      {% if page_obj.has_next %}
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
      <li class="page-item"> <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages}} &raquo;</a></li>
      {% endif %}

      </ul>
      <div class="chart">
        <canvas id="myChart" style="height: 50%; width:50%;"></canvas>
      </div>
   
 
      <script src="{% static 'js/stats.js' %}"> </script>
{% endblock %}

templates/expensesadd.html
{% extends 'main.html' %}

{% block title %}
{% if edit %}
Edit Expenses
{% else %}
Add New Expenses
{% endif %}
{% endblock title %}

{% block content %}
{% if edit %}
  <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->
  <h2></h2>
  <form class="form" method="post" action="{% url 'expenses:edit' ele.pk%}">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" >Amount</label>
        <input class="form-control" type="text" name="amount" value="{{ele.amount}}"/>
    </div>  
    <div class="mb-3">
        <label class="form-label">Category</label>
        <select class="form-select form-select-md" name='category'>
            <option value="{{ele.category}}" selected>{{ele.category}}</option>
           {% for i in category %}
            <option value="{{i.name}}">{{i.name}}</option>
           {% endfor %}
        </select>
    </div>  
    <div class="mb-3">
        <label class="form-label" >Date {{ele.date}}</label>
        <input placeholder="Date" name="date" class="form-control" type="text" onfocus="(this.type='date')" value="{{ele.date|date:'Y-m-d'}}" id="date">
        <!-- <input class="form-control" value="{{ele.date|date:'d/m/y'}}" type="date" name="date" /> -->
    </div>  
    <div class="mb-3">
        <label class="form-label" >Description</label>
        <input class="form-control" type="text" name="description" value="{{ele.description}}" />
    </div>  
      <input type="submit" class="btn btn-primary" />
  </form>
  {% else %}

  <!-- <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas> -->
  <h2></h2>
  <form class="form" method="post" action="{% url 'expenses:add' %}">
    {% csrf_token %}
    <div class="mb-3">
        <label class="form-label" >Amount</label>
        <input class="form-control" type="text" name="amount"/>
    </div>  
    <div class="mb-3">
        <label class="form-label">Category</label>
        <select class="form-select form-select-md" name='category'>
           {% for i in category %}
            <option value="{{i.name}}">{{i.name}}</option>
           {% endfor %}
        </select>
    </div>  
    <div class="mb-3">
        <label class="form-label" >Date</label>
        <input placeholder="Date" name="date" class="form-control" type="text" onfocus="(this.type='date')" id="date">
    </div>  
    <div class="mb-3">
        <label class="form-label" >Description</label>
        <input class="form-control" type="text" name="description"/>
    </div>  
      <input type="submit" class="btn btn-primary" />
  </form>
  {% endif %}
  {% endblock content %}

templates/main.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Finance Tracker</title>

    <!-- Bootstrap core CSS -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
<!-- <script src="{% static 'js/index.js' %}"></script> -->
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script><script src="{% static 'js/index.js' %}"></script>
<meta name="theme-color" content="#7952b3">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
  </head>
  <body style="color:darkslategray;">
    
    <header class="navbar navbar-dark sticky-top bg-info flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">Finance App</a>
      <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      {% if user.is_authenticated %}
      <p class="text-white h6">Welcome, {{user.username}}</p>
      {% endif %}
      <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          
          <!-- <a class="nav-link" href="">Logout</a> -->
        </li>
      </ul>
    </header>
    
    <div class="container-fluid">
      <div class="row">
        {% include "sider.html" %}
    
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h1 class="h2">{% block title %}Dashboard{% endblock title %}</h1>
          </div>
          {% if messages %}
          <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="alert alert-lg alert-{{ message.tags }}" {% endif %}>{{ message }}</li>
              {% endfor %}
          </ul>
          {% endif %}
            {% block content %}
            
            {% endblock content %}
      </div>
      <div class="footer mb-3">
        <h6><footer> &copy; Copyright <a href="https://portfolio-udit.herokuapp.com/">Udit Bhati</a> 2021</footer></h6>
       </div>
      </main>
      
    </div>

    

  <script src="{% static 'js/min.js' %}"></script>
</body>

</html>

templates/sider.html
{% block var %}
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-sticky pt-3">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'expenses:home' %}">
            <span data-feather="home"></span>
            Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'expenses:expenses' %}">
            <span data-feather="shopping-cart"></span>
            Expenses
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'income:income' %}">
            <span data-feather="dollar-sign"></span>
            Income
          </a>
        </li>
        </li>
      </ul>

      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>Summary</span>
        <!-- <a class="link-secondary" href="#" aria-label="Add a new report">
          <span data-feather="plus-circle"></span>
        </a> -->
      </h6>
      <ul class="nav flex-column mb-2">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'expenses:stat' %}">
            <span data-feather="file-text"></span>
            Expenses Summary
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'income:stat' %}">
            <span data-feather="file-text"></span>
            Income Summary
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'expenses:settings' %}">
            <span data-feather="settings"></span>
            Settings
          </a>
        </li>
      </ul>
    </div>
  </nav>
{% endblock %}

templates/stats.html
{% extends 'main.html' %}
{% load static %}
{% block title %}Expenses Statics{% endblock title %}
{% block content %}
<div class="chart-container" style="position: absolute; height:40vh; width:80vw">
    <canvas id="myChart2" ></canvas>
    <canvas id="myChart3"></canvas>
</div>


 
<script src="{% static 'js/stats.js' %}"> </script>
{% endblock content %}

templates/userpref.html
{% extends 'main.html' %}
{% block title %}User Preferences{% endblock title %}
{% block content %}
<div class="container mt-5">
<form method="post" action="{% url 'expenses:settings' %}">
    {% csrf_token %}
<select class="form-select form-select-lg mb-3 mt-5" name='currency'>
    <option selected>{{prev}}</option>
   {% for i in curr %}
    <option value="{{i.value}}">{{i.value}}</option>
   {% endfor %}
</select>
<input type="submit" class="btn btn-primary" />
</div>
</form>
{% endblock %}